<?php


// @codingStandardsIgnoreFile

/**
 * @var $block \Pointspay\Pointspay\Block\Info\Virtual
 * @var $escaper \Magento\Framework\Escaper
 */
if (!isset($escaper)) {
    $escaper = $block;
}

?>
<span><?= $escaper->escapeHtml(__('The payment has been completed with the following method:')); ?></span>
<br/>
<span><strong><?= $block->getPaymentTitleByFlavor($block->getInfo()->getAdditionalInformation('pointspay_flavor')) ?></strong></span>
<?= $escaper->escapeHtml($block->getChildHtml()); ?>
