<?php

/**
 * @var $block \Pointspay\Pointspay\Block\Form\Virtual
 * @var $escaper \Magento\Framework\Escaper
 */
if (!isset($escaper)) {
    $escaper = $block;
}
?>

<fieldset
    class="admin__fieldset payment-method"
    id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>"
    style="display: none">
    <div class="admin__field _required">
        <label for="pointspay_expires_at" class="admin__field-label">
               <span>
               <?= $escaper->escapeHtml(__('Payment link expires at')) ?>
               </span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="pointspay_expires_at" name="payment[pointspay_expires_at]"
                   title="<?= $escaper->escapeHtml(__("Date when the payment link will expire")) ?>"
                   class="required-entry admin__control-text"
                   value="<?= /* @noEscape */
                   $block->getInfoData('pointspay_expires_at') ?>"/>
        </div>
    </div>
</fieldset>
